/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99. DO NOT MODIFY.
*/
module Clash_Explicit_Mealy_mealy
    ( // Inputs
      input \#pTS  // clock
    , input \#pTS_0  // asynchronous reset: active high
    , input [1:0] i1

      // Outputs
    , output reg [3:0] \#tup_app_arg 
    );
  wire [2:0] n;
  wire [0:0] dir;
  wire [0:0] en;
  reg [2:0] s;

  always @(*) begin
    case(n)
      3'b000 : \#tup_app_arg  = 4'b0000;
      3'b001 : \#tup_app_arg  = 4'b0001;
      3'b010 : \#tup_app_arg  = 4'b0010;
      3'b011 : \#tup_app_arg  = 4'b0100;
      3'b100 : \#tup_app_arg  = 4'b1000;
      default : \#tup_app_arg  = 4'b0000;
    endcase
  end

  StepperMotor_next StepperMotor_next_n
  (.result (n),.dir (dir),.en (en),.state (s));

  assign dir = i1[1:1];

  assign en = i1[0:0];

  // register begin
  always @(posedge \#pTS  or posedge \#pTS_0 ) begin : Clash_Explicit_Mealy_mealy_register
    if (\#pTS_0 ) begin
      s <= 3'b000;
    end else begin
      s <= n;
    end
  end
  // register end
endmodule

