/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99. DO NOT MODIFY.
*/
module StepperMotor_stepperMotor
    ( // Inputs
      input [1:0] \$d(%,%) 
    , input [1:0] \in' 

      // Outputs
    , output reg [3:0] result
    );
  wire [3:0] \#app_arg ;

  Clash_Explicit_Mealy_mealy Clash_Explicit_Mealy_mealy_app_arg
  (.\#tup_app_arg  (\#app_arg )
  ,.\#pTS  (\$d(%,%) [1:1])
  ,.\#pTS_0  (\$d(%,%) [0:0])
  ,.i1 (\in' ));

  // register begin
  always @(posedge \$d(%,%) [1:1] or posedge \$d(%,%) [0:0]) begin : StepperMotor_stepperMotor_register
    if (\$d(%,%) [0:0]) begin
      result <= 4'b0000;
    end else begin
      result <= \#app_arg ;
    end
  end
  // register end
endmodule

