/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99. DO NOT MODIFY.
*/
module StepperMotor_next
    ( // Inputs
      input dir
    , input en
    , input [2:0] state

      // Outputs
    , output reg [2:0] result
    );
  reg [2:0] \#case_alt ;
  reg [2:0] \#case_alt_0 ;
  reg [2:0] \#case_alt_1 ;
  reg [2:0] \#case_alt_2 ;
  reg [2:0] \#case_alt_3 ;
  reg [2:0] \#case_alt_4 ;
  reg [2:0] \#case_alt_5 ;
  reg [2:0] \#case_alt_6 ;

  always @(*) begin
    case(state)
      3'b000 : result = \#case_alt_4 ;
      3'b001 : result = \#case_alt_2 ;
      3'b010 : result = \#case_alt_1 ;
      3'b011 : result = \#case_alt_0 ;
      3'b100 : result = \#case_alt ;
      default : result = 3'b000;
    endcase
  end

  always @(*) begin
    if(dir)
      \#case_alt  = \#case_alt_4 ;
    else
      \#case_alt  = \#case_alt_3 ;
  end

  always @(*) begin
    if(dir)
      \#case_alt_0  = \#case_alt_6 ;
    else
      \#case_alt_0  = \#case_alt_5 ;
  end

  always @(*) begin
    if(dir)
      \#case_alt_1  = \#case_alt_3 ;
    else
      \#case_alt_1  = \#case_alt_4 ;
  end

  always @(*) begin
    if(dir)
      \#case_alt_2  = \#case_alt_5 ;
    else
      \#case_alt_2  = \#case_alt_6 ;
  end

  always @(*) begin
    if(en)
      \#case_alt_3  = 3'b011;
    else
      \#case_alt_3  = 3'b000;
  end

  always @(*) begin
    if(en)
      \#case_alt_4  = 3'b001;
    else
      \#case_alt_4  = 3'b000;
  end

  always @(*) begin
    if(en)
      \#case_alt_5  = 3'b010;
    else
      \#case_alt_5  = 3'b000;
  end

  always @(*) begin
    if(en)
      \#case_alt_6  = 3'b100;
    else
      \#case_alt_6  = 3'b000;
  end
endmodule

