/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99. DO NOT MODIFY.
*/
module Top_stepperReg_0
    ( // Inputs
      input [1:0] \$d(%,%) 
    , input [16:0] eta2

      // Outputs
    , output wire [43:0] result
    );
  wire [35:0] \#app_arg ;
  wire [7:0] x;
  wire [143:0] y;
  wire [151:0] ds;
  wire [1:0] ds_fun_arg;

  assign result = {x,\#app_arg };

  // map begin
  genvar i;
  generate
  for (i=0; i < 18; i = i + 1) begin : map
    wire [7:0] map_in;
    wire [1:0] map_out;

    assign map_in = y[i*8+:8];
    assign map_out = {(map_in[(64'sd1)]) == (1'b1)
  ,(map_in[(64'sd0)]) == (1'b1)};
    assign \#app_arg [i*2+:2] = map_out;
  end
  endgenerate
  // map end

  assign x = ds[151:144];

  assign y = ds[143:0];

  assign ds_fun_arg = {\$d(%,%) [1:1]
                      ,\$d(%,%) [0:0]};

  Top_stepperReg Top_stepperReg_ds
  (.result (ds)
  ,.\$d(%,%)  (ds_fun_arg)
  ,.eta2 (eta2));
endmodule

